# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_content', models.TextField(blank=True)),
                ('last_edit', models.DateField(default=datetime.datetime.now, verbose_name='invoice date')),
            ],
        ),
    ]
