# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki_entry',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
