# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-16 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wiki_entry_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wiki_entry',
            new_name='Wikientry',
        ),
    ]
