# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20180720_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikientry',
            old_name='subject',
            new_name='title',
        ),
    ]
