# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20180720_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikientry',
            options={'get_latest_by': 'last_edit', 'ordering': ['-created_time', '-last_edit']},
        ),
        migrations.RemoveField(
            model_name='wikientry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='wikientry',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
