# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-18 15:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0003_auto_20180716_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='last_edit',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Last Edit'),
        ),
    ]
