# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_ref', models.CharField(blank=True, max_length=100)),
                ('our_ref', models.CharField(max_length=100)),
                ('invoice', models.FileField(upload_to='invoice/%Y/%M/')),
                ('approved', models.BooleanField(default=False)),
                ('invoice_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='invoice date')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('vat_number', models.IntegerField(blank=True, max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='invoices',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Supplier'),
        ),
    ]
