# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
