# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20180406_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
