# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoices_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='expense_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoices',
            name='purchased_item',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='invoices',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='payment_method',
            field=models.CharField(blank=True, default='Credit Card', max_length=100),
        ),
    ]
