# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20180629_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
