# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoices_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='currency',
            field=models.CharField(blank=True, default='\xa3', max_length=600),
        ),
    ]
